name: b2b_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ">=2.16.0 <3.0.0"

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_svg: ^0.22.0 # help us to use SVG in our app
  cached_network_image: ^3.2.0
  camera: ^0.9.7+1
  image: ^3.1.0
  image_picker: ^0.8.5+3
  graphql_flutter: ^5.0.1
  internet_connection_checker: ^0.0.1+3
  connectivity_plus: 2.2.1
  shared_preferences: 2.0.13
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.2.0
  location: ^4.2.0
  shimmer: ^2.0.0
  http: ^0.13.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter



flutter: 
  uses-material-design: true


  assets:
  - assets/images/
  - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300